# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

# Get the variable PROJECT_NAME from the environment or default to the CLI name
vars:
  PROJECT_NAME:
    sh: echo ${PROJECT_NAME:-technitiumdns-cli}
  XDG_BIN_HOME:
    sh: echo ${XDG_BIN_HOME:-~/.local/bin}
  DEFAULT_TARGET:
    sh: |
      OS=$(uname -s | tr '[:upper:]' '[:lower:]'); \
      ARCH=$(uname -m); \
      if [ "$ARCH" = "x86_64" ]; then ARCH="x64"; fi; \
      echo "bun-${OS}-${ARCH}"

# Set the parameter back to the environment to make it available for node operations if not already set
env:
  PROJECT_NAME: "{{.PROJECT_NAME}}"
  XDG_BIN_HOME: "{{.XDG_BIN_HOME}}"

tasks:
  init:
    silent: true
    cmds:
      - bun install
    sources:
      - node_modules
    generates:
      - bun.lock

  lint:
    silent: true
    desc: "Lint the SEA for $PROJECT_NAME"
    deps:
      - init
    cmds:
      - bun run lint
    sources:
      - "**/*.{ts,json,md,yaml}"

  lint:fix:
    desc: "Lint and fix the SEA for $PROJECT_NAME"
    silent: true
    deps:
      - init
    cmds:
      - bun run lint:fix
    sources:
      - src/**/*.ts

  format:
    silent: true
    desc: "Format the SEA for $PROJECT_NAME"
    deps:
      - init
    cmds:
      - bun run format
    sources:
      - "**/*.{ts,json,md,yaml}"

  build:
    silent: true
    desc: "Build the SEA for $PROJECT_NAME"
    deps:
      - init
      - lint:fix
      - format
    cmds:
      - mkdir -p dist
      - |
        TARGET_VALUE=${TARGET:-{{.DEFAULT_TARGET}}}
        TEMP_OUTFILE=./$PROJECT_NAME.tmp
        bun build --compile --minify --sourcemap src/main.ts --target "$TARGET_VALUE" --outfile "$TEMP_OUTFILE"
        mv "$TEMP_OUTFILE" {{.DIST_OUTFILE}}
    sources:
      - src/**/*.ts
    generates:
      - dist/{{.PROJECT_NAME}}
    vars:
      DIST_OUTFILE:
        sh: echo dist/${PROJECT_NAME:-technitiumdns-cli}

  build:linux:
    silent: true
    desc: "Cross-compile the SEA for Linux amd64"
    deps:
      - init
      - lint:fix
      - format
    cmds:
      - mkdir -p dist
      - |
        TARGET_VALUE=bun-linux-x64
        TEMP_OUTFILE=./$PROJECT_NAME-linux.tmp
        bun build --compile --minify --sourcemap src/main.ts --target "$TARGET_VALUE" --outfile "$TEMP_OUTFILE"
        mv "$TEMP_OUTFILE" {{.LINUX_OUTFILE}}
        rm -f "$TEMP_OUTFILE"
    sources:
      - src/**/*.ts
    generates:
      - dist/{{.PROJECT_NAME}}-linux
    vars:
      LINUX_OUTFILE:
        sh: echo dist/${PROJECT_NAME:-technitiumdns-cli}-linux

  build:windows:
    silent: true
    desc: "Cross-compile the SEA for Windows amd64"
    deps:
      - init
      - lint:fix
      - format
    cmds:
      - mkdir -p dist
      - |
        TARGET_VALUE=bun-windows-x64
        TEMP_OUTFILE=./$PROJECT_NAME-windows.tmp
        bun build --compile --minify --sourcemap src/main.ts --target "$TARGET_VALUE" --outfile "$TEMP_OUTFILE"
        mv "$TEMP_OUTFILE" {{.WINDOWS_OUTFILE}}
        rm -f "$TEMP_OUTFILE"
    sources:
      - src/**/*.ts
    generates:
      - dist/{{.PROJECT_NAME}}-windows.exe
    vars:
      WINDOWS_OUTFILE:
        sh: echo dist/${PROJECT_NAME:-technitiumdns-cli}-windows.exe

  build:darwin:
    silent: true
    desc: "Cross-compile the SEA for macOS arm64"
    deps:
      - init
      - lint:fix
      - format
    cmds:
      - mkdir -p dist
      - |
        TARGET_VALUE=bun-darwin-arm64
        TEMP_OUTFILE=./$PROJECT_NAME-darwin.tmp
        bun build --compile --minify --sourcemap src/main.ts --target "$TARGET_VALUE" --outfile "$TEMP_OUTFILE"
        mv "$TEMP_OUTFILE" {{.DARWIN_OUTFILE}}
        rm -f "$TEMP_OUTFILE"
    sources:
      - src/**/*.ts
    generates:
      - dist/{{.PROJECT_NAME}}-darwin
    vars:
      DARWIN_OUTFILE:
        sh: echo dist/${PROJECT_NAME:-technitiumdns-cli}-darwin

  clean:
    silent: true
    desc: "Remove build artifacts for $PROJECT_NAME"
    cmds:
      - |
        rm -rf dist
        rm -f "./{{.PROJECT_NAME}}.tmp"
        find . -maxdepth 1 -name '.*.bun-build' -delete
    vars:
      DIST_OUTFILE:
        sh: echo dist/${PROJECT_NAME:-technitiumdns-cli}

  run:
    silent: true
    desc: "Run the SEA for $PROJECT_NAME"
    deps:
      - build
    cmds:
      - echo "Running SEA for $PROJECT_NAME..."
      - "{{.DIST_OUTFILE}} --help"
    vars:
      DIST_OUTFILE:
        sh: echo dist/${PROJECT_NAME:-technitiumdns-cli}

  dist:
    desc: "Copy the current platform build to XDG_BIN_HOME"
    deps:
      - build
    cmds:
      - mkdir -p ${XDG_BIN_HOME:-~/.local/bin}
      - cp {{.DIST_OUTFILE}} {{.OUTFILE}}
      - chmod +x {{.OUTFILE}}
      - rm ${XDG_BIN_HOME:-~/.local/bin}/tdns
      - ln -s {{.OUTFILE}} ${XDG_BIN_HOME:-~/.local/bin}/tdns
    vars:
      DIST_OUTFILE:
        sh: echo dist/${PROJECT_NAME:-technitiumdns-cli}
      OUTFILE:
        sh: echo ${XDG_BIN_HOME:-~/.local/bin}/${PROJECT_NAME:-technitiumdns-cli}
